name: Build macOS App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          brew install jq
          brew install make

      - name: Prepare macOS .app structure
        run: |
          APP_DIR="NvimUnity.app"
          mkdir -p "$APP_DIR/Contents/MacOS"
          mkdir -p "$APP_DIR/Contents/Resources"

          cp nvim-unity-osx/install.sh "$APP_DIR/Contents/MacOS/nvimunity"
          chmod +x "$APP_DIR/Contents/MacOS/nvimunity"

          cp nvim-unity-osx/Contents/Resources/nvimunity.png "$APP_DIR/Contents/Resources/"

          # (Opcional) Converter PNG para ICNS
          if command -v iconutil &> /dev/null; then
            sips -s format icns "$APP_DIR/Contents/Resources/nvimunity.png" --out "$APP_DIR/Contents/Resources/nvimunity.icns"
          fi

      - name: Create DMG
        run: |
          hdiutil create -volname "NvimUnity" -srcfolder "NvimUnity.app" -ov -format UDZO "nvim-unity.dmg"

      - name: Upload DMG artifact
        uses: actions/upload-artifact@v3
        with:
          name: nvim-unity.dmg
          path: nvim-unity.dmg

