name: Build macOS App

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'nvim-unity-osx/**'
  pull_request:
    branches:
      - master
    paths:
      - 'nvim-unity-osx/**'

jobs:
  build:
    runs-on: macos-latest

    steps:
      # 1. Checa o código do repositório
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Instala dependências necessárias (como jq, xcodebuild, etc)
      - name: Install dependencies
        run: |
          brew install jq
          brew install make
          brew install xcodebuild

      # 3. Cria a estrutura do App
      - name: Build the macOS app
        run: |
          mkdir -p NvimUnity.app/Contents/MacOS
          mkdir -p NvimUnity.app/Contents/Resources

          # Copia o script para o MacOS
          cp install.sh NvimUnity.app/Contents/MacOS/nvimunity
          chmod +x NvimUnity.app/Contents/MacOS/nvimunity

          # Copia o ícone
          cp icons/nvimunity.png NvimUnity.app/Contents/Resources/nvimunity.png

          # Converter ícone para .icns (opcional)
          iconutil --convert icns --output NvimUnity.app/Contents/Resources/nvimunity.icns NvimUnity.app/Contents/Resources/nvimunity.png || true

      # 4. Empacotar como DMG
      - name: Create DMG
        run: |
          hdiutil create -volname "NvimUnity" -srcfolder NvimUnity.app -ov -format UDZO /tmp/nvim-unity.dmg

      # 5. Fazer upload do .dmg como artefato
      - name: Upload DMG artifact
        uses: actions/upload-artifact@v4
        uses: actions/download-artifact@v4
        with:
          name: nvim-unity.dmg
          path: /tmp/nvim-unity.dmg

